### PR TITLE
Treat single dash as argument instead of option

### LINKED ISSUE #2: Cannot parse "-"
When passing "-" to a command to give it stdin, the command returns:
`'target/x86_64-unknown-linux-gnu…' terminated by signal SIGILL (Illegal instruction)`

### PR DESCRIPTION
**Pull request by DoumanAsh**
Fixes #2

Still treat `--` as error

### CODE REVIEW

**Comment by DoumanAsh** [comment]
@emmatebibyte you can give it a try if you want.

**Comment by emmatebibyte** [comment]
Thank you so much! I'll take a look when I'm home from work.

**Comment by emmatebibyte** [comment]
```rs
    Updating git repository `https://github.com/DoumanAsh/arg.rs`
   Compiling coreutils v0.0.1 (/home/emma/src/TiB/yac/coreutils)
error: unexpected closing delimiter: `}`
  --> src/cat.rs:30:10
   |
30 | #[derive(Args, Debug)]
   |          ^^^^
   |          |
   |          this opening brace...
   |          ...matches this closing brace
   |          unexpected closing delimiter
   |
   = note: this error originates in the derive macro `Args` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc-macro derive panicked
  --> src/cat.rs:30:10
   |
30 | #[derive(Args, Debug)]
   |          ^^^^
```
code:
```rs
// Copyright (c) 2022 YAC
// SPDX-License-Identifier: AGPL-3.0-or-later

/* This file is part of YAC coreutils.
 *
 * YAC coreutils is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * YAC coreutils is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

use std::env;
use std::fs::{File, read_to_string};
use std::io;
use std::io::{ BufRead, Write };
use std::os::unix::io::FromRawFd;

use arg::Args;

use sysexits::ExitCode;

#[derive(Args, Debug)]
struct Arguments {
  #[arg(short = "u")]
  u: bool,

  paths: Vec<String>,
}

fn main() -> ExitCode {
  let mut arguments = env::args().collect::<Vec<String>>();
  let argv0 = arguments.remove(0);

  let mut args = Arguments::from_args(arguments
    .iter()
    .map(String::as_str)
    .collect::<Vec<&str>>()
  ).unwrap();

  let mut output = String::new();

  if args.paths.is_empty() { args.paths.push("-".to_string()); }

  for path in args.paths {
    if path == "-" {
      loop {
        match io::stdin().lock().read_line(&mut output) {
          Ok(EOF) => if EOF == 0 { break },
          Err(_) => {
            eprintln!("Usage: {} [options...] [files...]", &argv0);
            return ExitCode::Usage;
          },
        };
      }
    } else {
      match read_to_string(&path) {
        Ok(contents) => { output.push_str(&contents) },
        Err(_) => {
          eprintln!("{}: {}: No such file or directory.", &argv0, &path);
          return ExitCode::NoInput;
        },
      };
    }
    print!("{}", output);
    output.clear();
  }
  match io::stdout().flush() {
    Ok(_) => return ExitCode::Ok,
    Err(_) => {
      eprintln!("{}: Cannot write to stdout", &argv0);
      return ExitCode::OsErr;
    },
  };
}
```

**Comment by DoumanAsh** [comment]
Sorry, my bad, I fixed it

**Comment by emmatebibyte** [comment]
Works perfectly :) thank you so much!

**Pull request merged**
